version: 2.1

jobs:
  dockerhub-p3-uda:
      machine:
        image: ubuntu-2204:2022.04.2
      steps:
        - checkout
        - run:
            name: Login to dockerhub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run:
            name: Deploy udagram-api-feed to Dockerhub
            command: |
              docker build -t udagram-api-feed ./udagram-api-feed
              docker tag udagram-api-feed khanglt/udagram-api-feed:v1
              docker push khanglt/udagram-api-feed:v1
        - run:
            name: Deploy udagram-api-user to Dockerhub
            command: |
              docker build -t udagram-api-user ./udagram-api-user
              docker tag udagram-api-user khanglt/udagram-api-user:v1
              docker push khanglt/udagram-api-user:v1
        - run:
            name: Deploy udagram-frontend to Dockerhub
            command: |
              docker build -t udagram-frontend ./udagram-frontend
              docker tag udagram-frontend khanglt/udagram-frontend:v2
              docker push khanglt/udagram-frontend:v2
        - run:
            name: Deploy udagram-reverseproxy to Dockerhub
            command: |
              docker build -t udagram-reverseproxy ./udagram-reverseproxy
              docker tag udagram-reverseproxy khanglt/udagram-reverseproxy:v1
              docker push khanglt/udagram-reverseproxy:v1
workflows:
  default:
    jobs:
      - dockerhub-p3-uda