apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-uda
  labels:
    app: frontend-app-uda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app-uda
  template:
    metadata:
      labels:
        app: frontend-app-uda
    spec:
      containers:
      - name: udagram-frontend
        image: khanglt1/udagram-frontend:v2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1m"
          requests:
            cpu: "1m"